name: Build, push, and deploy to GCP

on:
  push:
    branches:
      - master
    paths-ignore:
      - "doc/**"
      - "**/*.md"

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Extract version of Go to use
        run: echo "GOVERSION=$(cat go.mod | grep -w "go" | awk ' { print $2 } ' | grep -w "^[^v]")" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Cache Go modules
        uses: actions/cache@v3
        id: go-mod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test armor
        run: make test

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: $${IMAGE}

  deploy-dev-gcp:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml
          VARS: .nais/dev-vars.yml

  #deploy-prod-gcp:
  #  name: Deploy to prod-gcp
  #  needs: deploy-dev-gcp
  #  runs-on: ubuntu-20.04
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: nais/deploy/actions/deploy@v1
  #      env:
  #        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  #        CLUSTER: prod-gcp
  #        RESOURCE: .nais/nais.yml
  #        VARS: .nais/prod-vars.yml